tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "bat"
brew "composer"
brew "exa"
brew "exercism"
brew "git-delta"
brew "go"
brew "neovim", link: false
brew "nvm"
brew "starship"
brew "tmux"

cask "brave-browser"
cask "clipy"
cask "docker"
cask "font-jetbrains-mono"
cask "iriunwebcam"
cask "ishowu"
cask "iterm2"
cask "itsycal"
cask "lando"
cask "notion"
cask "obs"
cask "slack"
cask "spectacle"
cask "spotify"
cask "streamlabs-obs"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
