brew 'fish'
brew 'golang'
brew 'nvm'
brew 'youtube-dl'

cask '1password'
cask 'acquia-dev-desktop'
cask 'dropbox'
cask 'google-chrome'
cask 'hipchat'
cask 'keepingyouawake'
cask 'postgres'
cask 'skype'
cask 'spectacle'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoomus'
